### ISSUE TITLE
error kali domainOsint.py line 10

### ISSUE THREAD

**Issue by sonofapharmacist** [DataSploit/datasploit#101]
just running first time after successful setup ./datasploit.py or python datasploit.py or python2 datasploit.py
```
Traceback (most recent call last):
  File "./domainOsint.py", line 10, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

```

**Comment by nkpanda** [comment]
try python domainOsint.py -d xyz.com (or any domain name it will work)

**Comment by upgoingstar** [comment]
Please open this issue if unresolved.
