### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rajaol** [DataSploit/datasploit#106]
Just typed the following domain name to test.
./datasploit.py  domain.com
Worked till Hidden links then thrown the following error

Traceback (most recent call last):
  File "./domainOsint.py", line 374, in <module>
    main()
  File "./domainOsint.py", line 345, in main
    do_everything(domain)
  File "./domainOsint.py", line 263, in do_everything
    subdomains_from_netcraft(domain)
  File "/datasploit/domain_subdomains.py", line 152, in subdomains_from_netcraft
    if num_subdomains[0] != str(0):
IndexError: list index out of range

Same error for some other domains as well. 

raj@deb:~/datasploit$ ./domain_subdomains.py <some-domain.com>
---> Finding subdomains, will be back soon with list. 

Traceback (most recent call last):
  File "./domain_subdomains.py", line 201, in <module>
    main()
  File "./domain_subdomains.py", line 191, in main
    subdomains_from_netcraft(domain)
  File "./domain_subdomains.py", line 152, in subdomains_from_netcraft
    if num_subdomains[0] != str(0):
IndexError: list index out of range

**Comment by upgoingstar** [comment]
do this still persist? if yes, then will review the pull request and accept. 

thanks.

**Comment by rfzabick** [comment]
No, this was fixed in the "Adding functionality to generate HTML reports for a domain" checkin.

**Comment by rajaol** [comment]
Yes. Thank You. Its fixed.
