### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc2 in position 0: unexpected end of data

### ISSUE THREAD

**Issue by rajaol** [DataSploit/datasploit#107]
Domain name used sumeru.com
./datasploit.py sumeru.com

Reached till TXT Records

File "./domainOsint.py", line 374, in <module>
    main()
  File "./domainOsint.py", line 345, in main
    do_everything(domain)
  File "./domainOsint.py", line 130, in do_everything
    print "\t%s" % (y)
  File "/usr/local/lib/python2.7/dist-packages/dns/rdata.py", line 202, in __str__
    return self.to_text()
  File "/usr/local/lib/python2.7/dist-packages/dns/rdtypes/txtbase.py", line 46, in to_text
    txt += '%s"%s"' % (prefix, dns.rdata._escapify(s))
  File "/usr/local/lib/python2.7/dist-packages/dns/rdata.py", line 100, in _escapify
    packed = struct.pack('!B', c).decode()
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc2 in position 0: unexpected end of data

**Comment by rajaol** [comment]
Any update or work around to solve this ?


Traceback (most recent call last):
  File "./domainOsint.py", line 551, in <module>
    main()
  File "./domainOsint.py", line 522, in main
    do_everything(domain, output, active)
  File "./domainOsint.py", line 162, in do_everything
    lhtml += "<li class='collection-item'>%s</li>" % y
  File "/usr/local/lib/python2.7/dist-packages/dns/rdata.py", line 202, in __str__
    return self.to_text()
  File "/usr/local/lib/python2.7/dist-packages/dns/rdtypes/txtbase.py", line 46, in to_text
    txt += '%s"%s"' % (prefix, dns.rdata._escapify(s))
  File "/usr/local/lib/python2.7/dist-packages/dns/rdata.py", line 100, in _escapify
    packed = struct.pack('!B', c).decode()
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc2 in position 0: unexpected end of data
