### ISSUE TITLE
ImportError: No module named config

### ISSUE THREAD

**Issue by gitfuzzing** [DataSploit/datasploit#129]
python domainOsint.py -h

Traceback (most recent call last):
  File "domainOsint.py", line 13, in <module>
    run(domain)
  File "domainOsint.py", line 8, in run
    osint_runner.run("domain", "domain", domain)
  File "/root/datasploit-master/osint_runner.py", line 14, in run
    x = importlib.import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/datasploit-master/domain/domain_emailhunter.py", line 4, in <module>
    import config as cfg
ImportError: No module named config

**Comment by upgoingstar** [comment]
have you renamed the config_sample.py to config.py?

**Comment by minskzxc** [comment]
User Input: arianagrande.com
Looks like a DOMAIN, running domainOsint...

Traceback (most recent call last):
  File "./datasploit.py", line 55, in <module>
    main(user_input, options.output)
  File "./datasploit.py", line 43, in main
    domainOsint.run(user_input, output)
  File "/etc/datasploit/domainOsint.py", line 9, in run
    osint_runner.run("domain", "domain", domain, output)
  File "/etc/datasploit/osint_runner.py", line 18, in run
    x = importlib.import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/etc/datasploit/domain/domain_GooglePDF.py", line 8, in <module>
    from termcolor import colored
ImportError: No module named termcolor

**Comment by upgoingstar** [comment]
Fixed in last major release.
