### ISSUE TITLE
Can't find any way to download Wappalyzer to make it work.

### ISSUE THREAD

**Issue by S3RKK** [DataSploit/datasploit#130]
Traceback (most recent call last):
  File "./domainOsint.py", line 11, in <module>
    from Wappalyzer import Wappalyzer, WebPage
ImportError: No module named Wappalyzer

when I do pip install -r requirements.txt it gives me error setting up in the ending with the xml stuff

**Comment by S3RKK** [comment]
Fixed last issue now I get this issue instead.
Traceback (most recent call last):
  File "./domainOsint.py", line 12, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by S3RKK** [comment]
You know how I fix that? :D cuz I think the requirements.txt is broken or something, I can't use anything tbh.

**Comment by upgoingstar** [comment]
Fixed this one in the last commit, please git pull once and try again. If this still persists, please let me know.
