### ISSUE TITLE
I got the same error again...

### ISSUE THREAD

**Issue by S3RKK** [DataSploit/datasploit#132]
Still get the error when doing pip install -r requirements.txt how do I fix this ? :(

**Comment by decapstrike** [comment]
So I'm having the same, using Kali Linux 2017.1 fully updated. Here's how I fix it:

apt-get install libxml2-dev libxslt1-dev python-dev
apt-get install zlib1g-dev

Do that, then run the pip install -r requirements.txt and it works. 

Anyway to have those added to the requirements installer?

**Comment by KunalAggarwal** [comment]
These requirements cannot be installed using pip. We plan to include a
installer script later to install all required OS dependencies.

**Comment by decapstrike** [comment]
Understood. Could it be added to the installation instructions then?

**Comment by S3RKK** [comment]
I agree, I will try your way of fixing it decapstrike, if it doesn't work then idk what to do. But if it works you guys should tell them how you fix it because I've waited a long time for a fix :D

**Comment by S3RKK** [comment]
No still wont work it gives me this error.
Traceback (most recent call last):
  File "./emailOsint.py", line 13, in <module>
    run(email)
  File "./emailOsint.py", line 8, in run
    osint_runner.run("email", "emails", email)
  File "/root/datasploit/osint_runner.py", line 14, in run
    x = importlib.import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/datasploit/emails/email_slideshare.py", line 7, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by OctAg0nO** [comment]
im running kali 2017.1  full updated

**Comment by xKygecHuk** [comment]
have the same problem.;/

Traceback (most recent call last):
  File "./emailOsint.py", line 10, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by tomikreed** [comment]
Having the same issue: 

Traceback (most recent call last):
  File "datasploit.py", line 55, in <module>
    main(user_input, options.output)
  File "datasploit.py", line 43, in main
    domainOsint.run(user_input, output)
  File "/root/Resources/Discovery/datasploit/domainOsint.py", line 9, in run
    osint_runner.run("domain", "domain", domain, output)
  File "/root/Resources/Discovery/datasploit/osint_runner.py", line 18, in run
    x = importlib.import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/Resources/Discovery/datasploit/domain/domain_forumsearch.py", line 5, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by c4nc** [comment]
Same here (OSX Sierra):

[-] Skipping Censys because it is marked as disabled.
Traceback (most recent call last):
  File "datasploit.py", line 55, in <module>
    main(user_input, options.output)
  File "datasploit.py", line 43, in main
    domainOsint.run(user_input, output)
  File "/Users/xxx/Tools/datasploit/domainOsint.py", line 9, in run
    osint_runner.run("domain", "domain", domain, output)
  File "/Users/xxx/Tools/datasploit/osint_runner.py", line 18, in run
    x = importlib.import_module(module_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/xxx/Tools/datasploit/domain/domain_forumsearch.py", line 5, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/site-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/site-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by nati0n** [comment]
@c4nc, @xKygecHuk, @S3RKK and any others with the 
_AttributeError: 'module' object has no attribute '\_base'_ error, try: 
`pip install --upgrade beautifulsoup4`
`pip install --upgrade html5lib `

Seems to be the same issue as [here (#104)](https://github.com/DataSploit/datasploit/issues/104)

**Comment by sithrocker** [comment]
I have fixed this before, but forgot where it was that i did it... 

[-] Skipping Censys because it is marked as disableds because it is marked as disabled
