### ISSUE TITLE
Still errors with modules

### ISSUE THREAD

**Issue by S3RKK** [DataSploit/datasploit#134]
I followed a fix commented on my last post but it still does not work. I get this error 
Traceback (most recent call last):
  File "datasploit.py", line 54, in <module>
    main(user_input)
  File "datasploit.py", line 36, in main
    emailOsint.run(user_input)
  File "/root/datasploit/emailOsint.py", line 8, in run
    osint_runner.run("email", "emails", email)
  File "/root/datasploit/osint_runner.py", line 14, in run
    x = importlib.import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/datasploit/emails/email_slideshare.py", line 7, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
something is wrong with my modules please help me! I've been trying to use this program for more then a week now! :(

**Comment by blahdidbert** [comment]
This is the same issue as [number 136](https://github.com/DataSploit/datasploit/issues/136).
For this particular issue I found that down grading to this version of html5lib fixed this particular issue. 

    pip install --upgrade html5lib==1.0b8

Please also make sure you are using the directions found here.
http://www.datasploit.info/

**Comment by S3RKK** [comment]
Thanks a lot :D worked @blahdidbert
