### ISSUE TITLE
ImportError: No module named core

### ISSUE THREAD

**Issue by OctAg0nO** [DataSploit/datasploit#135]
im getting this error when i run   C_FORCE_ROOT=root celery -A core worker -l info --concurrency 20..

output

datasploit# C_FORCE_ROOT=root celery -A core worker -l info --concurrency 20       
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 30, in main
    main()
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 309, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 469, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 489, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/utils.py", line 235, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 492, in symbol_by_name
    return symbol_by_name(name, imp=imp)
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/__init__.py", line 96, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named core

**Comment by OctAg0nO** [comment]
im running kali linux 2017.1 full updated

**Comment by blahdidbert** [comment]
The reason you are getting this error is because there is no longer a "core" directory. I think the creators might have missed updating their link, this is the correct one:

http://www.datasploit.info/setupGuide/

As you will notice, there are no longer any need for rabbit, mongo, or celery packages.

**Comment by upgoingstar** [comment]
We have restructured the whole code and made it a framework. Guides we have right now are not fully updated.  We are working hard to get them published asap. 

Thanks.
