### ISSUE TITLE
why is no one helping us?

### ISSUE THREAD

**Issue by S3RKK** [DataSploit/datasploit#136]
So many people have commented the same module problem, something is wrong with the modules. Please fix it.

**Comment by S3RKK** [comment]
Or help us fix it.

**Comment by S3RKK** [comment]
Here's how the error could look like, it has always something to do with bs4 

Traceback (most recent call last):
  File "./datasploit.py", line 54, in <module>
    main(user_input)
  File "./datasploit.py", line 36, in main
    emailOsint.run(user_input)
  File "/root/datasploit2/emailOsint.py", line 8, in run
    osint_runner.run("email", "emails", email)
  File "/root/datasploit2/osint_runner.py", line 14, in run
    x = importlib.import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/datasploit2/emails/email_slideshare.py", line 7, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by 0xbadshah** [comment]
Testing is in process. Will patch it soon.

**Comment by S3RKK** [comment]
Oh thank god!!!!! Finally! Any ETA when it is released?

**Comment by 0xbadshah** [comment]
No estimation of date. A complete review and patch is being done. So please wait. Its good that you found a bug. It would be great if you could try to resolve.

**Comment by S3RKK** [comment]
I've sat here since my first comment, not gotten it to work, trust me man I've tried fixing it so many times :P

**Comment by blahdidbert** [comment]
For this particular issue I found that down grading to this version of html5lib fixed this partular issue. 

    pip install --upgrade html5lib==1.0b8

Also it would be great if same documentation is used across the board. For example, the first link here:  
> http://datasploit.readthedocs.io/en/latest/

Says to still use MongoDB and Rabbit

Then this link is posted and it doesn't have those steps at all:  
> http://www.datasploit.info/

**Comment by upgoingstar** [comment]
Apologies for the delayed response. Has been tied up with other work. Advice from @blahdidbert should have solved the issue.
