### ISSUE TITLE
KeyError on pastes scripts in domain and emails modules

### ISSUE THREAD

**Issue by S3RKK** [DataSploit/datasploit#137]
I feel like I am the only one posting issues, and it feels like I am retarded. But I just wanna use this tool very bad and want it to work so :D I fixed my old issue now, I get something with google. 

Traceback (most recent call last):
  File "./datasploit.py", line 54, in <module>
    main(user_input)
  File "./datasploit.py", line 36, in main
    emailOsint.run(user_input)
  File "/root/datasploit2/emailOsint.py", line 8, in run
    osint_runner.run("email", "emails", email)
  File "/root/datasploit2/osint_runner.py", line 23, in run
    data = x.main(m_input)
  File "/root/datasploit2/emails/email_pastes.py", line 61, in main
    data = google_search(email)
  File "/root/datasploit2/emails/email_pastes.py", line 44, in google_search
    if int(data['searchInformation']['totalResults']) > 0:
KeyError: 'searchInformation'

This is when trying to find information about an email address. I do get some results but then this comes.

**Comment by S3RKK** [comment]
It comes when this step comes "Finding Paste(s)"

**Comment by KunalAggarwal** [comment]
We'll be pushing code in a while to handle this error in domain and emails modules. This generally happens when the daily API usage gets exhausted.

Regards,
Kunal

**Comment by KunalAggarwal** [comment]
Was fixed with commit 6ab57b399e381e172a0dca057db6365f8f860202
