### ISSUE TITLE
ImportError: No module named termcolor

### ISSUE THREAD

**Issue by minskzxc** [DataSploit/datasploit#162]
User Input: arianagrande.com
Looks like a DOMAIN, running domainOsint...

Traceback (most recent call last):
  File "./datasploit.py", line 55, in <module>
    main(user_input, options.output)
  File "./datasploit.py", line 43, in main
    domainOsint.run(user_input, output)
  File "/etc/datasploit/domainOsint.py", line 9, in run
    osint_runner.run("domain", "domain", domain, output)
  File "/etc/datasploit/osint_runner.py", line 18, in run
    x = importlib.import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/etc/datasploit/domain/domain_GooglePDF.py", line 8, in <module>
    from termcolor import colored
ImportError: No module named termcolor

**Comment by upgoingstar** [comment]
Have you installed python requirements? You can run following command.
sudo pip --ignore-installed -r requirements.txt
