### ISSUE TITLE
JSON error while running domainOsint.py

### ISSUE THREAD

**Issue by eigenstein** [DataSploit/datasploit#166]
[+] Extracting subdomains from Certificate Transparency Reports

Traceback (most recent call last):
  File "domainOsint.py", line 17, in <module>
    run(domain, options.output)
  File "domainOsint.py", line 9, in run
    osint_runner.run("domain", "domain", domain, output)
  File "/etc/datasploit/osint_runner.py", line 29, in run
    data = x.main(m_input)
  File "/etc/datasploit/domain/domain_subdomains.py", line 121, in main
    subdomain_list = subdomains_from_google_ct(domain, subdomain_list)
  File "/etc/datasploit/domain/domain_subdomains.py", line 102, in subdomains_from_google_ct
    obj = json.loads('('.join(requests.get(url).text.split('(')[1:])[:-3])
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by beanbagginz** [comment]
same error as above. any update?

**Comment by upgoingstar** [comment]
Solved with #159
