### ISSUE TITLE
TypeError: string indices must be integers, not str

### ISSUE THREAD

**Issue by basketas** [DataSploit/datasploit#167]
---> Finding Paste(s)..

[+] 11 results found

Traceback (most recent call last):
  File "/root/Desktop/datasploit/datasploit.py", line 55, in <module>
    main(user_input, options.output)
  File "/root/Desktop/datasploit/datasploit.py", line 37, in main
    emailOsint.run(user_input, output)
  File "/root/Desktop/datasploit/emailOsint.py", line 9, in run
    osint_runner.run("email", "emails", email, output)
  File "/root/Desktop/datasploit/osint_runner.py", line 31, in run
    x.output(data, m_input)
  File "/root/Desktop/datasploit/emails/email_pastes.py", line 84, in output
    print "Title: %s\nURL: %s\nSnippet: %s\n" % (x['title'].encode('utf-8'), colorize(x['link'].encode('utf-8')), colorize(x['snippet'].encode('utf-8')))
TypeError: string indices must be integers, not str

**Comment by KunalAggarwal** [comment]
Closing, fixed with commit 2c21d78b54eb2f1e22a785d74dfbf3f5eec7ea6a
