### ISSUE TITLE
Issue with SSL Verification when using usernameOsint

### ISSUE THREAD

**Issue by krlplm** [DataSploit/datasploit#187]
Below are the error logs while trying to use "usernameOsint"

[+] Checking Gitlab user details

Traceback (most recent call last):
  File "/etc/datasploit/datasploit.py", line 87, in <module>
    main(sys.argv[1:])
  File "/etc/datasploit/datasploit.py", line 80, in main
    usernameOsint.run(user_input, output)
  File "/etc/datasploit/usernameOsint.py", line 9, in run
    osint_runner.run("username", "username", username, output)
  File "/etc/datasploit/osint_runner.py", line 29, in run
    data = x.main(m_input)
  File "/etc/datasploit/username/username_gitlabdetails.py", line 29, in main
    if (requests.head(url).status_code == 200):
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 97, in head
    return request('head', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by upgoingstar** [comment]
Fixed in https://github.com/DataSploit/datasploit/commit/f3ab0d39bd78c0a64f31848042ca7fc5571db0d1
