### ISSUE TITLE
'ascii' codec can't decode byte 0xc2 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by upgoingstar** [DataSploit/datasploit#192]
python datasploit.py -i sumeru.com 

Traceback (most recent call last):
  File "datasploit.py", line 88, in <module>
    main(sys.argv[1:])
  File "datasploit.py", line 78, in main
    domainOsint.run(user_input, output)
  File "/Users/shubhammittal/Documents/Pythoncodes/datasploit_parent/datasploit_v1.0/datasploit/domainOsint.py", line 9, in run
    osint_runner.run("domain", "domain", domain, output)
  File "/Users/shubhammittal/Documents/Pythoncodes/datasploit_parent/datasploit_v1.0/datasploit/osint_runner.py", line 31, in run
    x.output(data, m_input)
  File "/Users/shubhammittal/Documents/Pythoncodes/datasploit_parent/datasploit_v1.0/datasploit/domain/domain_dnsrecords.py", line 54, in output
    print "\t%s" % y
  File "/Library/Python/2.7/site-packages/dns/rdata.py", line 202, in __str__
    return self.to_text()
  File "/Library/Python/2.7/site-packages/dns/rdtypes/txtbase.py", line 46, in to_text
    txt += '%s"%s"' % (prefix, dns.rdata._escapify(s))
  File "/Library/Python/2.7/site-packages/dns/rdata.py", line 100, in _escapify
    packed = struct.pack('!B', c).decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 0: ordinal not in range(128)

**Comment by upgoingstar** [comment]
Fixed in commit ec1d94ca687448ea6b40a3f65b643abec46919d5
