### ISSUE TITLE
Travis-CI user checks

### ISSUE THREAD

**Issue by g3td0wn** [DataSploit/datasploit#194]
Don't know if it is bug or my fault, but searching for a nickname produces following:
Traceback (most recent call last):
  File "./datasploit.py", line 88, in <module>
    main(sys.argv[1:])
  File "./datasploit.py", line 81, in main
    usernameOsint.run(user_input, output)
  File "/opt/datasploit/usernameOsint.py", line 9, in run
    osint_runner.run("username", "username", username, output)
  File "/opt/datasploit/osint_runner.py", line 29, in run
    data = x.main(m_input)
  File "/opt/datasploit/username/username_traviscidetails.py", line 37, in main
    token = TravisPy.github_auth(cfg.github_travis_key)
  File "/usr/lib/python2.7/site-packages/travispy/travispy.py", line 77, in github_auth
    contents = get_response_contents(response)
  File "/usr/lib/python2.7/site-packages/travispy/_helpers.py", line 34, in get_response_contents
    raise TravisError(contents)
travispy.errors.TravisError: [403] not a Travis user
Then datasploit terminates.
Googled it, but no answers given.
Github token presents.

**Comment by KhasMek** [comment]
@g3td0wn would you rebase your instance on the latest code, retest, close this issue if resolved and let us know if your issue is still present, please? #171 should have fixed your issue here.

**Comment by 0xbadshah** [comment]
Hey @g3td0wn , any updates ?
