### ISSUE TITLE
Failed to extract subdomains from Certificate Transparency Reports

### ISSUE THREAD

**Issue by PlatinumDragon** [DataSploit/datasploit#202]
When running domainOsint it crashes on extracting subdomains from Certificate Transparency Reports

 [+] Extracting subdomains from Certificate Transparency Reports
Traceback (most recent call last):
  File "./datasploit.py", line 88, in <module>
    main(sys.argv[1:])
  File "./datasploit.py", line 78, in main
    domainOsint.run(user_input, output)
  File "/opt/datasploit/domainOsint.py", line 9, in run
    osint_runner.run("domain", "domain", domain, output)
  File "/opt/datasploit/osint_runner.py", line 29, in run
    data = x.main(m_input)
  File "/opt/datasploit/domain/domain_subdomains.py", line 154, in main
    subdomain_list, other_related_domain_list = subdomains_from_google_ct(domain, subdomain_list, other_related_domain_list)\
  File "/opt/datasploit/domain/domain_subdomains.py", line 137, in subdomains_from_google_ct
    nextpage_details = dd[0][3]
IndexError: list index out of rang

**Comment by 0xbadshah** [comment]
I am facing the same issue.

**Comment by AntonDykyi** [comment]
Same here:

```
Traceback (most recent call last):
  File "domainOsint.py", line 17, in <module>
    run(domain, options.output)
  File "domainOsint.py", line 9, in run
    osint_runner.run("domain", "domain", domain, output)
  File "/private/etc/datasploit/osint_runner.py", line 28, in run
    data = x.main(m_input)
  File "/private/etc/datasploit/domain/domain_subdomains.py", line 154, in main
    subdomain_list, other_related_domain_list = subdomains_from_google_ct(domain, subdomain_list, other_related_domain_list)\
  File "/private/etc/datasploit/domain/domain_subdomains.py", line 137, in subdomains_from_google_ct
    nextpage_details = dd[0][3]
IndexError: list index out of range
```

**Comment by KunalAggarwal** [comment]
Handling done with latest commit https://github.com/DataSploit/datasploit/commit/5a3132dc70465bb9a94a8fa85eea156ea5ed7cdc
