### ISSUE TITLE
Issue when running ./datasploit.py 

### ISSUE THREAD

**Issue by anonoperation** [DataSploit/datasploit#203]
User Input: www.arianagrande.com
Looks like a Username, running Username_OSINT...

Traceback (most recent call last):
  File "./usernameOsint.py", line 9, in <module>
    import config as cfg
  File "/root/DataSploit/config.py", line 23
    twitter_consumer_secret""
                            ^
SyntaxError: invalid syntax

**Comment by KunalAggarwal** [comment]
Looks like a syntax error in your config. Would you please share the contents of your config.py here.
Or you could edit line 23 in your config.py to look like this:

`twitter_consumer_secret=""`

**Comment by 0xbadshah** [comment]
Hey @anonoperation , please pull the latest Datasploit code and try again. Please comment if you are facing any issues.
