### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Vhaka** [DataSploit/datasploit#206]
How can I fix these errors??

Traceback (most recent call last):
  File "./datasploit.py", line 89, in <module>
    main(sys.argv[1:])
  File "./datasploit.py", line 79, in main
    domainOsint.run(user_input, output)
  File "/etc/datasploit/domainOsint.py", line 9, in run
    osint_runner.run("domain", "domain", domain, output)
  File "/etc/datasploit/osint_runner.py", line 17, in run
    x = importlib.import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/etc/datasploit/domain/domain_subdomains.py", line 6, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by Vhaka** [comment]
Traceback (most recent call last):
  File "domainOsint.py", line 17, in <module>
    run(domain, options.output)
  File "domainOsint.py", line 9, in run
    osint_runner.run("domain", "domain", domain, output)
  File "/root/datasploit/osint_runner.py", line 17, in run
    x = importlib.import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/datasploit/domain/domain_subdomains.py", line 6, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by Vhaka** [comment]
OMG i tried and tried and tried to get this tool running and it failed, i did everything by the book and still not working...i give up.

**Comment by MelissaMV** [comment]
I'm having the same issue someone pls help

**Comment by KunalAggarwal** [comment]
Same issue opened earlier #137. 
Run the following command to downgrade the html5lib library:

`pip install --upgrade html5lib==1.0b8`

This will fix the issue.

**Comment by MelissaMV** [comment]
Thank you! @KunalAggarwal it worked! :)
