### ISSUE TITLE
ImportError: No module named pip

### ISSUE THREAD

**Issue by offshores** [DataSploit/datasploit#224]
Please provide the following details.

### Host System

- OS : Mac 10.13.2
- Python version (`python --version`) : 2.7.10

### Error Description

Please provide the details of the error. Try to provide the **output** and also **steps to reproduce** (if possible).

If you cloned Datasploit, also provide the output of `git log -n 1 --pretty=format:"%B"`.

$ ./datasploit.py 
Traceback (most recent call last):
  File "./datasploit.py", line 4, in <module>
    dep_check.check_dependency()
  File "/Users/computer/tools/datasploit/dep_check.py", line 11, in check_dependency
    pip_list = sorted([(i.key) for i in pip.get_installed_distributions()])
NameError: global name 'pip' is not defined
computers-iMac:datasploit computer$ nano dep_check.py
computers-iMac:datasploit computer$ ./datasploit.py 
Traceback (most recent call last):
  File "./datasploit.py", line 3, in <module>
    import dep_check
  File "/Users/computer/tools/datasploit/dep_check.py", line 1, in <module>
    import pip
ImportError: No module named pip
datasploit computer$ pip install pip
Requirement already satisfied: pip in /usr/local/lib/python2.7/site-packages
datasploit computer$

**Comment by 0xbadshah** [comment]
Hey @offshores do you have `pip` installed on your system ? What's the output of `pip freeze` ?

**Comment by 0xbadshah** [comment]
Hey @offshores , any updates ?

**Comment by securitybites** [comment]
Getting the same error here. I have pip installed. The output of pip freeze is:

~~~
anyjson==0.3.3
attrs==17.4.0
BeautifulSoup==3.2.1
beautifulsoup4==4.4.1
billiard==3.3.0.23
bs4==0.0.1
clearbit==0.1.4
config==0.3.9
configobj==5.0.6
datasploit==1.0
dnspython==1.14.0
funcsigs==1.0.2
future==0.15.2
google-api-python-client==1.6.6
html5lib==1.0.1
httplib2==0.11.1
idna==2.1
ipaddr==2.2.0
ipwhois==0.15.1
json2html==1.0.1
lxml==3.6.0
more-itertools==4.1.0
netaddr==0.7.19
oauth2client==4.1.2
oauthlib==2.0.7
piplapis-python==5.1.0
pluggy==0.6.0
praw==5.4.0
prawcore==0.14.0
py==1.5.3
pyasn1==0.4.2
pyasn1-modules==0.2.1
pymongo==3.3.0
pytest==3.5.0
pytest-rerunfailures==4.0
python-Wappalyzer==0.2.2
python-whois==0.6.2
pytz==2016.6.1
requests==2.10.0
requests-file==1.4
requests-oauthlib==0.8.0
rsa==3.4.2
simplejson==3.8.2
six==1.11.0
termcolor==1.1.0
tld==0.7.9
tldextract==2.0.1
tqdm==4.7.6
TravisPy==0.3.5
tweepy==3.5.0
update-checker==0.16
uritemplate==3.0.0
webencodings==0.5.1

~~~
