### ISSUE TITLE
AttributeError: 'module' object has no attribute '_base'

### ISSUE THREAD

**Issue by krlplm** [DataSploit/datasploit#230]
Please provide the following details.

### Host System

- OS : Ubuntu 16.04, 64 bit
- Python version (`python --version`) : 
2.7.12
### Error Description
Tried running the below command,
python datasploit.py -i google.com

**Error output**
```
['adium-theme-ubuntu', 'anyjson', 'ascii-graph', 'beautifulsoup', 'beautifulsoup4', 'billiard', 'bs4', 'certstream', 'cffi', 'chardet', 'clearbit', 'config', 'configobj', 'cryptography', 'dnspython', 'entropy', 'enum34', 'future', 'geoip', 'google-api-python-client', 'html5lib', 'httplib2', 'idna', 'ipaddr', 'ipaddress', 'ipwhois', 'json2html', 'lxml', 'ndg-httpsclient', 'netaddr', 'numpy', 'oauth2client', 'oauthlib', 'oletools', 'pip', 'piplapis-python', 'ply', 'py', 'pyasn1', 'pyasn1-modules', 'pycparser', 'pygeoip', 'pymongo', 'pyopenssl', 'pytest', 'pytest-rerunfailures', 'python-levenshtein', 'python-wappalyzer', 'python-whois', 'pytz', 'requests', 'requests-file', 'requests-oauthlib', 'rsa', 'setuptools', 'simplejson', 'six', 'ssdeep', 'termcolor', 'tld', 'tldextract', 'tqdm', 'travispy', 'tweepy', 'unity-lens-photos', 'uritemplate', 'urllib3', 'webencodings', 'websocket-client', 'wheel', 'whois']
True

  ____/ /____ _ / /_ ____ _ _____ ____   / /____   (_)/ /_
 / __  // __ `// __// __ `// ___// __ \ / // __ \ / // __/
/ /_/ // /_/ // /_ / /_/ /(__  )/ /_/ // // /_/ // // /_
\__,_/ \__,_/ \__/ \__,_//____// .___//_/ \____//_/ \__/
                              /_/

           Open Source Assistant for #OSINT
               www.datasploit.info


Target: google.com
Looks like a DOMAIN, running domainOsint...

Traceback (most recent call last):
  File "datasploit.py", line 112, in <module>
    main(sys.argv[1:])
  File "datasploit.py", line 68, in main
    auto_select_target(single_input, output)
  File "datasploit.py", line 104, in auto_select_target
    domainOsint.run(target, output)
  File "/root/datasploit/domainOsint.py", line 9, in run
    osint_runner.run("domain", "domain", domain, output)
  File "/root/datasploit/osint_runner.py", line 17, in run
    x = importlib.import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/datasploit/domain/domain_history.py", line 6, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
```

Please provide the details of the error. Try to provide the **output** and also **steps to reproduce** (if possible).

If you cloned Datasploit, also provide the output of `git log -n 1 --pretty=format:"%B"`.
```
# git log -n 1 --pretty=format:"%B"
Merge branch 'master' of https://github.com/DataSploit/datasploit
```

**Comment by 0xbadshah** [comment]
Hey @krlplm , 
Please do the following:
1. Pull the latest Datasploit code
2. Execute `pip install --upgrade --force-reinstall -r requirements.txt`

Then try to execute datasploit against your target. If you find some issues, please comment.

**Comment by krlplm** [comment]
Hello @Chan9390 

It looks like the suggestion has worked. Thanks much.

However, while running against an email id, I see the below error,
```
---> Searching Email in DarkNet

Traceback (most recent call last):
  File "datasploit.py", line 112, in <module>
    main(sys.argv[1:])
  File "datasploit.py", line 68, in main
    auto_select_target(single_input, output)
  File "datasploit.py", line 101, in auto_select_target
    emailOsint.run(target, output)
  File "/root/datasploit/emailOsint.py", line 9, in run
    osint_runner.run("email", "emails", email, output)
  File "/root/datasploit/osint_runner.py", line 28, in run
    data = x.main(m_input)
  File "/root/datasploit/emails/email_hacked_emails.py", line 24, in main
    data = json.loads(req.text.encode('UTF-8'))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by 0xbadshah** [comment]
This is a bug. Will check it soon.

**Comment by ankushgoel27** [comment]
i am seeing the same bug

**Comment by JhonShell** [comment]
The best way to fix it  is install the following : 
pip install --upgrade beautifulsoup4
pip install --upgrade html5lib
pip install
https://pypi.python.org/packages/cf/9a/50d3844d67fe5507217fd47c9e382e769ab5f7d967b41c25ba3712c441c3/cfscrape-1.9.1.tar.gz
