### ISSUE TITLE
emailOsint.py could not work

### ISSUE THREAD

**Issue by Francis75848** [DataSploit/datasploit#244]
Please provide the following details.

### Host System

- OS : Kali 2017.3 (vbox)
- Python version (`python --version`) : 2.7

### Error Description

root@kali:~/datasploit# python emailOsint.py XXXXXXX@gmail.com
[-] Skipping Clearbit because it is marked as disabled.

---> Checking breach status in HIBP (@troyhunt)

---> Searching Whoismind for associated domains

Traceback (most recent call last):
  File "emailOsint.py", line 17, in <module>
    run(email, options.output)
  File "emailOsint.py", line 9, in run
    osint_runner.run("email", "emails", email, output)
  File "/root/datasploit/osint_runner.py", line 28, in run
    data = x.main(m_input)
  File "/root/datasploit/emails/email_whoismind.py", line 28, in main
    if at.text in at['href']:
  File "/usr/local/lib/python2.7/dist-packages/bs4/element.py", line 1011, in __getitem__
    return self.attrs[key]
KeyError: 'href'

If you cloned Datasploit, also provide the output of `git log -n 1 --pretty=format:"%B"`.

root@kali:~/datasploit# git log -n 1 --pretty=format:"%B"
Merge pull request #235 from KhasMek/redditdetails

username: add reddit details lookup

**Comment by KhasMek** [comment]
Did you install all the requirements with the command `pip install --upgrade --force-reinstall -r requirements.txt`?

**Comment by triclorne** [comment]
I had a similar issue and I did 
1. a dist-upgrade of the OS
2. pip install --upgrade --force-reinstall -r requirements.txt
3. pip install datasploit
