### ISSUE TITLE
AttributeError: 'module' object has no attribute 'get_install_distrobutions'

### ISSUE THREAD

**Issue by GamingFTW** [DataSploit/datasploit#254]
### Host System
VMware Workstation 14
- OS : Kali Linux 2018.2 KDE
- Python version (`python --version`) : Python 2.7.15rc1 

`root@Kali-VM:/etc/datasploit# python2 datasploit.py uakron.edu
Traceback (most recent call last):
  File "datasploit.py", line 4, in <module>
    dep_check.check_dependency()
  File "/etc/datasploit/dep_check.py", line 11, in check_dependency
    pip_list = sorted([(i.key) for i in pip.get_installed_distributions()])
AttributeError: 'module' object has no attribute 'get_installed_distributions'
`
### Error Description
I am running standalone version of Datasploit and I keep getting this error. Even after doing:
`ip install --upgrade --force-reinstall -r requirements.txt `

**Comment by jx6f** [comment]
I was in the same boat. Following patch works for me.

```diff
diff --git a/dep_check.py b/dep_check.py
index 474251b..8088ec6 100644
--- a/dep_check.py
+++ b/dep_check.py
@@ -1,4 +1,7 @@
-import pip
+try:
+    from pip._internal.utils.misc import get_installed_distributions
+except ImportError:
+    from pip import get_installed_distributions
 import sys
 
 def check_dependency():
@@ -8,7 +11,7 @@ def check_dependency():
     with open('requirements.txt') as f:
         list_deps = f.read().splitlines()
 
-    pip_list = sorted([(i.key) for i in pip.get_installed_distributions()])
+    pip_list = sorted([(i.key) for i in get_installed_distributions()])
 
     for req_dep in list_deps:
         if req_dep not in pip_list:
```

**Comment by janki7227** [comment]
C:\Users\xyz\PycharmProjects\test3\venv\Scripts\python.exe C:/Users/xyz/PycharmProjects/test3/test3
Traceback (most recent call last):
  File "C:/Users/xyz/PycharmProjects/test3/test3", line 44, in <module>
    p.add_header('Content-Disposition', "attachment; filename= %d", abc.txt)
AttributeError: module 'abc' has no attribute 'txt'



Facing same trouble 

Process finished with exit code 1
