### ISSUE TITLE
Getting error dep_check.py

### ISSUE THREAD

**Issue by makamkkumar** [DataSploit/datasploit#255]
Please provide the following details.

### Host System

- OS : Ubuntu 16.04 LTS
- Python version (`python --version`) : 2.7.12

### Error Description
F:~/datasploit$  python datasploit.py test.com
Traceback (most recent call last):
  File "datasploit.py", line 4, in <module>
    dep_check.check_dependency()
  File "/home/ws2/datasploit/dep_check.py", line 11, in check_dependency
    pip_list = sorted([(i.key) for i in pip.get_installed_distributions()])
AttributeError: 'module' object has no attribute 'get_installed_distributions'

Please provide the details of the error. Try to provide the **output** and also **steps to reproduce** (if possible).

If you cloned Datasploit, also provide the output of `git log -n 1 --pretty=format:"%B"`.
commit c7c9ef4bc867b42edefec6cae7f2c2e201e3da01
Author: upgoingstar <upgoingstaar@gmail.com>
Date:   Fri Mar 9 07:57:40 2018 +0530

    Moving Certificate Transparency Reports from google to CRT.sh

commit 602efc6bc1faa13ff555cc5db2ec5ff4a9e918f9
Merge: 8504aee 554df33
Author: Shubham mittal <upgoingstaar@gmail.com>
Date:   Thu Jan 18 19:40:05 2018 +0530

    Merge pull request #235 from KhasMek/redditdetails
    
    username: add reddit details lookup

commit 8504aee39fa7c796575b437ebfc076385efe0cc0
Merge: d82df97 41bd014
Author: Shubham mittal <upgoingstaar@gmail.com>
Date:   Thu Jan 18 19:14:37 2018 +0530

    Merge pull request #225 from ishamfazal/issu01-twitter_suspended_user
    
    Suspended user unhandled exception

**Comment by makamkkumar** [comment]
Output of pip freeze command is given below:-
adium-theme-ubuntu==0.3.4
anyjson==0.3.3
atomicwrites==1.1.5
attrs==18.1.0
BeautifulSoup==3.2.1
beautifulsoup4==4.6.0
billiard==3.5.0.3
bs4==0.0.1
cachetools==2.1.0
certifi==2018.4.16
chardet==3.0.4
clearbit==0.1.7
config==0.3.9
configobj==5.0.6
dnspython==1.15.0
funcsigs==1.0.2
future==0.16.0
google-api-python-client==1.7.3
google-auth==1.5.0
google-auth-httplib2==0.0.3
html5lib==1.0.1
httplib2==0.11.3
idna==2.6
ipaddr==2.2.0
ipwhois==1.0.0
json2html==1.2.1
lxml==4.2.1
more-itertools==4.2.0
netaddr==0.7.19
oauthlib==2.1.0
piplapis-python==5.1.4
pluggy==0.6.0
praw==5.4.0
prawcore==0.14.0
py==1.5.3
pyasn1==0.4.3
pyasn1-modules==0.2.1
pymongo==3.6.1
PySocks==1.6.8
pytest==3.6.1
pytest-rerunfailures==4.1
python-Wappalyzer==0.2.2
python-whois==0.7.0
pytz==2018.4
requests==2.18.4
requests-file==1.4.3
requests-oauthlib==1.0.0
rsa==3.4.2
simplejson==3.15.0
six==1.11.0
termcolor==1.1.0
tld==0.7.10
tldextract==2.2.0
tqdm==4.23.4
TravisPy==0.3.5
tweepy==3.6.0
unity-lens-photos==1.0
update-checker==0.16
uritemplate==3.0.0
urllib3==1.22
vboxapi==1.0
webencodings==0.5.1
youtube-dl==2018.3.14

**Comment by james-see** [comment]
I have this same issue.

**Comment by james-see** [comment]
To workaround this issue, I simply commented out the 

```
#import dep_check
#dep_check.check_dependency()
``` 
section in `datasploit.py`.

**Comment by dexter-dz** [comment]
after commenting out 
#import dep_check
#dep_check.check_dependency()

I get this error now :
Traceback (most recent call last):
  File "datasploit.py", line 16, in <module>
    from tld import get_tld
ImportError: No module named tld
