### ISSUE TITLE
Error on module emailOsint.py 

### ISSUE THREAD

**Issue by frajico** [DataSploit/datasploit#261]
Please provide the following details.

### Host System

- OS : Ubuntu 18.04
- Python version (`python --version`) : python --version

### Error Description

Error when input to datasploit.py or emailOsint.py is an email

python emailOsint.py abuse@microsoft.com
[-] Skipping Clearbit because it is marked as disabled.

---> Searching Whoismind for associated domains

Traceback (most recent call last):
  File "emailOsint.py", line 17, in <module>
    run(email, options.output)
  File "emailOsint.py", line 9, in run
    osint_runner.run("email", "emails", email, output)
  File "/home/osint/frameworks/datasploit/osint_runner.py", line 28, in run
    data = x.main(m_input)
  File "/home/osint/frameworks/datasploit/emails/email_whoismind.py", line 28, in main
    if at.text in at['href']:
  File "/home/osint/.local/lib/python2.7/site-packages/bs4/element.py", line 1011, in __getitem__
    return self.attrs[key]
KeyError: 'href'

python emailOsint.py abuse@microsoft.com
[-] Skipping Clearbit because it is marked as disabled.

---> Searching Whoismind for associated domains

Traceback (most recent call last):
  File "emailOsint.py", line 17, in <module>
    run(email, options.output)
  File "emailOsint.py", line 9, in run
    osint_runner.run("email", "emails", email, output)
  File "/home/osint/frameworks/datasploit/osint_runner.py", line 28, in run
    data = x.main(m_input)
  File "/home/osint/frameworks/datasploit/emails/email_whoismind.py", line 28, in main
    if at.text in at['href']:
  File "/home/osint/.local/lib/python2.7/site-packages/bs4/element.py", line 1011, in __getitem__
    return self.attrs[key]
KeyError: 'href'

If you cloned Datasploit, also provide the output of `git log -n 1 --pretty=format:"%B"`.

Moving Certificate Transparency Reports from google to CRT.sh
%

**Comment by KhasMek** [comment]
Open your copy of [email_whoismind.py](https://github.com/DataSploit/datasploit/blob/master/emails/email_whoismind.py#L10) and rename `Enabled=True` to `Enabled=False`. That should sort out that particular issue. If you run into any other modules that fail, do the same thing to disable them as well.
