### ISSUE TITLE
"clear bit marked as disabled" error

### ISSUE THREAD

**Issue by Exotic-Algorithms** [DataSploit/datasploit#263]
OS: Kali Linux 2.0
root@kali:~# datasploit -i legendaryalgorithms@protonmail.com
True

  ____/ /____ _ / /_ ____ _ _____ ____   / /____   (_)/ /_
 / __  // __ `// __// __ `// ___// __ \ / // __ \ / // __/
/ /_/ // /_/ // /_ / /_/ /(__  )/ /_/ // // /_/ // // /_
\__,_/ \__,_/ \__/ \__,_//____// .___//_/ \____//_/ \__/
                              /_/

           Open Source Assistant for #OSINT
               www.datasploit.info

Target: legendaryalgorithms@protonmail.com
Looks like an EMAIL, running emailOsint...

[-] Skipping Clearbit because it is marked as disabled.

---> Searching Whoismind for associated domains

Traceback (most recent call last):
  File "datasploit.py", line 112, in <module>
    main(sys.argv[1:])
  File "datasploit.py", line 68, in main
    auto_select_target(single_input, output)
  File "datasploit.py", line 101, in auto_select_target
    emailOsint.run(target, output)
  File "/usr/share/datasploit/emailOsint.py", line 9, in run
    osint_runner.run("email", "emails", email, output)
  File "/usr/share/datasploit/osint_runner.py", line 28, in run
    data = x.main(m_input)
  File "/usr/share/datasploit/emails/email_whoismind.py", line 28, in main
    if at.text in at['href']:
  File "/usr/lib/python2.7/dist-packages/bs4/element.py", line 1011, in __getitem__
    return self.attrs[key]
KeyError: 'href'

**Comment by sh0ra1t** [comment]
well i got this problem too.

it is related to osint_runner.py 

any one can help?
