### ISSUE TITLE
dep_check.py fails because pip.get_installed_distributions does not work

### ISSUE THREAD

**Issue by NetworkJack2** [DataSploit/datasploit#268]
Please provide the following details.

### Host System

- OS : 
Starch Loonix
$ uname -a
Linux titanium 4.18.5-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 24 12:48:58 UTC 2018 x86_64 GNU/Linux
- Python version (`python --version`) : 
$ python2 --version
Python 2.7.15
### Error Description
Traceback (most recent call last):
  File "datasploit.py", line 4, in <module>
    dep_check.check_dependency()
  File "/home/jack/Documents/github-tools/datasploit/dep_check.py", line 11, in check_dependency
    pip_list = sorted([(i.key) for i in pip.get_installed_distributions()])
AttributeError: 'module' object has no attribute 'get_installed_distributions
Please provide the details of the error. Try to provide the **output** and also **steps to reproduce** (if possible).

If you cloned Datasploit, also provide the output of `git log -n 1 --pretty=format:"%B"`.

The error is this line in dep_check.py:

    pip_list = sorted([(i.key) for i in pip.get_installed_distributions()])

As per: https://github.com/pypa/pip/issues/5243

Python recommends using  pkg_resources.working_set from python-setuptools instead.

EDIT: Pull Request here: https://github.com/DataSploit/datasploit/pull/269

**Comment by KhasMek** [comment]
This issue is a duplicate of #255 which already has a fix submitted in PR #262. Please check currently submitted issues before creating new ones.

**Comment by manishj1996** [comment]
Alternatively, you can add the following line: `import pkg_resources`
And replace `pip_list = sorted([(i.key) for i in pip.get_installed_distributions()])`
with `pip_list = sorted([(i.key) for i in pkg_resources.working_set])`
