### ISSUE TITLE
Trying luck with PunkSpider does not work!

### ISSUE THREAD

**Issue by k4n4n** [DataSploit/datasploit#271]
datasploit does not work, when try integrate some API, this happens:

---> Trying luck with PunkSpider

Traceback (most recent call last):
  File "datasploit.py", line 112, in <module>
    main(sys.argv[1:])
  File "datasploit.py", line 68, in main
    auto_select_target(single_input, output)
  File "datasploit.py", line 104, in auto_select_target
    domainOsint.run(target, output)
  File "/home/root/CTI/datasploit-master/domainOsint.py", line 9, in run
    osint_runner.run("domain", "domain", domain, output)
  File "/home/root/CTI/datasploit-master/osint_runner.py", line 28, in run
    data = x.main(m_input)
  File "/home/root/CTI/datasploit-master/domain/domain_checkpunkspider.py", line 40, in main
    return checkpunkspider(reversed_domain)
  File "/home/root/CTI/datasploit-master/domain/domain_checkpunkspider.py", line 24, in checkpunkspider
    req = requests.post("http://www.punkspider.org/service/search/detail/" + reversed_domain, verify=False)
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/api.py", line 112, in post
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/api.py", line 58, in request
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/sessions.py", line 508, in request
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/sessions.py", line 618, in send
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/adapters.py", line 508, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.punkspider.org', port=80): Max retries exceeded with url: /service/search/detail/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6115a05190>: Failed to establish a new connection: [Errno 111] Connection refused',))

This happens when connecting to www.punkspider.org fails the connection. Verifying punkspider is down and changing its domain to https://punk.sh/ but it is not up there either

**Comment by highmeh** [comment]
Having the same issue - If you're running ./datasploit.py -i <term> and don't need PunkSpider specifically, as a workaround, change "ENABLED: TRUE" in ./datasploit/domain/domain_checkpunkspider.py to "ENABLED: FALSE". It doesn't fix the root cause but lets you run datasploit without it failing out. Note that I also had to change "ENABLED: FALSE" in ./datasploit/domain/domain_subdomains.py as that bombed out on me as well.

**Comment by bwhack16** [comment]
@highmeh I am still receiving the same error after the above updates. Are there any steps required after changing the code?

**Comment by eddiezab** [comment]
I'm not sure if the issue you were having in November is the same issue as of now, but it looks like punkspider.com is resolving to localhost. I don't know on the permanence of this issue, but it looks as an alternative to the solution @highmeh posted, you should just be able to delete the ./datasploit/domain/domain_checkpunkspider.py file

**Comment by kawaxi** [comment]
same error here, please let me know how we can contribute to fix it.

**Comment by jepunband** [comment]
punkspider is down for good!. like @highmeh said deleting domain_checkpunkspider.py is the best option.
