### ISSUE TITLE
Traceback Error running emailOsint

### ISSUE THREAD

**Issue by MannyPython** [DataSploit/datasploit#275]
### Host System

- OS :  Manjaro Linux 18.0 (xfce)
- Python version (`python --version`) : Python 2.7 and Python 3.7

### Error Description
manjaro@manjaro-pc /u/s/datasploit> python2 datasploit.py -i example@gmail.com
True

Target: example@gmail.com
Looks like an EMAIL, running emailOsint...

Traceback (most recent call last):
  File "datasploit.py", line 112, in <module>
    main(sys.argv[1:])
  File "datasploit.py", line 68, in main
    auto_select_target(single_input, output)
  File "datasploit.py", line 101, in auto_select_target
    emailOsint.run(target, output)
  File "/usr/share/datasploit/emailOsint.py", line 9, in run
    osint_runner.run("email", "emails", email, output)
  File "/usr/share/datasploit/osint_runner.py", line 17, in run
    x = importlib.import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/share/datasploit/emails/email_hacked_emails.py", line 7, in <module>
    import cfscrape
ImportError: No module named cfscrape

Please provide the details of the error. Try to provide the **output** and also **steps to reproduce** (if possible).
I have installed using pacman, uninstalled and removed datasploit directory and reinstalled using datasploit's official installation guide, my config.py file has all of the API Keys registered from the datasploit installation manual, I have tried: pip install --upgrade --force-reinstall -r requirements.txt with pip2 and pip, and am currently using datasploit with pip2 9.0 as was a solution to a previous problem I had trying to run datasploit with the current version of pip2. 

I changed email_whoismind.py ENABLE = True to ENABLE = False on a previous install, however I still get every other traceback error listed. 
If you cloned Datasploit, also provide the output of `git log -n 1 --pretty=format:"%B"`.

**Comment by MannyPython** [comment]
Well, I fixed it by adding the third google API key in config.py, installing requirements.txt via pip2 18.0, then downgrading pip2 to 9.0.1 and then executing attacks. But this is ridiculous to have to do every time I want to use datasploit, so I just run datasploit in a python environment now with an isolated downgraded pip 9.0.1 so that it doesn't conflict with anything else.
