### ISSUE TITLE
Problem installing requirements

### ISSUE THREAD

**Issue by KnightTrek** [DataSploit/datasploit#280]
Hello! I have a problem when I try to install the requirements, I get the next error:
python3 -m pip install -r requirements.txt
Collecting anyjson (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/c3/4d/d4089e1a3dd25b46bebdb55a992b0797cff657b4477bc32ce28038fdecbc/anyjson-0.3.3.tar.gz
Collecting beautifulsoup (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/1e/ee/295988deca1a5a7accd783d0dfe14524867e31abb05b6c0eeceee49c759d/BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-z8y5fh4t/beautifulsoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-z8y5fh4t/beautifulsoup/
I'm using Kali Linux

**Comment by alvahdati** [comment]
Hi. Exactly the same problem on Kali 2019.1. No solution after a couple on months??

**Comment by alvahdati** [comment]
building with pip2 solved the problem. so:
1)  pip2 install --upgrade --force-reinstall -r requirements.txt
then build with pip again:
2) pip install --upgrade --force-reinstall -r requirements.txt

**Comment by rebl0x3r** [comment]
Well, install them manually : 

`while read line; do pip install $line; done < requirements.txt`

Fixed => Close.
