### ISSUE TITLE
Error execute datasploit

### ISSUE THREAD

**Issue by tXambe** [DataSploit/datasploit#284]
Please provide the following details.

### Host System

- OS : Linux K1 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-2kali1 (2019-05-15) x86_64 GNU/Linux
- Python version (`python --version`) : Python 2.7.16

### Error Description

When I execute python datasploit.py domain.com I got this error:
Traceback (most recent call last):
  File "datasploit.py", line 4, in <module>
    dep_check.check_dependency()
  File "/opt/OSINT/datasploit/dep_check.py", line 11, in check_dependency
    pip_list = sorted([(i.key) for i in pip.get_installed_distributions()])
AttributeError: 'module' object has no attribute 'get_installed_distributions'

**Comment by antihackme** [comment]
i am also getting the same error :(

**Comment by danbeavin** [comment]
I found as a temp way around this issue to go into the datasploit.py file and comment out the import check_dep line and the line below. This seems to allow the tool to work without checking dependencies.

**Comment by pdelteil** [comment]
Did you get any errors while installed the required python packages?

Try running this:

 pip install --upgrade  -r requirements.txt

**Comment by tXambe** [comment]
No and and I used "pip install --upgrade -r requirements.txt"

**Comment by rebl0x3r** [comment]
Simple Fix:

Get into the Directory, and type:

```
sed -i 's/dep_check.check_dependency()/#/g' datasploit.py
sed -i 's/import dep_check/#/g' datasploit.py
```

Fixed => close.
