### ISSUE TITLE
Issue with datasploit

### ISSUE THREAD

**Issue by antihackme** [DataSploit/datasploit#287]
Please provide the following details.

### Host System

- OS :  parrot os
- Python version (`python --2.7 ) : 

### Error Description

$python datasploit.py -h
Traceback (most recent call last):
  File "datasploit.py", line 4, in <module>
    dep_check.check_dependency()
  File "/home/antihack/datasploit/dep_check.py", line 11, in check_dependency
    pip_list = sorted([(i.key) for i in pip.get_installed_distributions()])
AttributeError: 'module' object has no attribute 'get_installed_distributions'

**Comment by danbeavin** [comment]
I found as a temp way around this issue to go into the datasploit.py file and comment out the import check_dep line and the line below.  This seems to allow the tool to work without checking dependencies.
