### ISSUE TITLE
datasploit error

### ISSUE THREAD

**Issue by MahmoudOsama1** [DataSploit/datasploit#294]
Please provide the following details.

### Host System

- OS : Kali
- Python version (`python --version`) : Python 2.7.17

### Error Description
root@kali:~/datasploit# ./datasploit.py networkarab.com
True
usage: datasploit.py [-h] [-i SINGLE_TARGET] [-f FILE_TARGET] [-a] [-q]
                     [-o OUTPUT]
datasploit.py: error: unrecognized arguments: networkarab.com
root@kali:~/datasploit# domainOsint.py networkarab.com
bash: domainOsint.py: command not found
root@kali:~/datasploit# domainOsint.py -i networkarab.com
bash: domainOsint.py: command not found
root@kali:~/datasploit# python domainOsint.py networkarab.com
[-] Skipping Googlepdf because it is marked as disabled.
[-] Skipping Zoomeye because it is marked as disabled.
[-] Skipping Urlscanio because it is marked as disabled.

[+] Checking for Google tracking codes.

[-] spyonweb_access_token not configured
[!] Error: No SpyOnWeb API token found. Skipping

---> Harvesting Email Addresses:.

[-] emailhunter not configured

[-] Emailhunter API key not configured, skipping Email Search.
Please refer to http://datasploit.readthedocs.io/en/latest/apiGeneration/.

---> Searching Github for domain results

[-] github_access_token not configured

[-] Github Access Token not configured, skipping Github Search.
Please refer to http://datasploit.readthedocs.io/en/latest/apiGeneration/.

---> Searching through WikiLeaks

---> Trying luck with PunkSpider

Traceback (most recent call last):
  File "domainOsint.py", line 17, in <module>
    run(domain, options.output)
  File "domainOsint.py", line 9, in run
    osint_runner.run("domain", "domain", domain, output)
  File "/root/datasploit/osint_runner.py", line 28, in run
    data = x.main(m_input)
  File "/root/datasploit/domain/domain_checkpunkspider.py", line 40, in main
    return checkpunkspider(reversed_domain)
  File "/root/datasploit/domain/domain_checkpunkspider.py", line 24, in checkpunkspider
    req = requests.post("http://www.punkspider.org/service/search/detail/" + reversed_domain, verify=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.punkspider.org', port=80): Max retries exceeded with url: /service/search/detail/com.networkarab (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f25078b9690>: Failed to establish a new connection: [Errno 111] Connection refused',))

If you cloned Datasploit, also provide the output of `git log -n 1 --pretty=format:"%B"`.

**Comment by jan-kwiatkowski** [comment]
Yeah i also have an issue on that.

`requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.punkspider.org', port=80): Max retries exceeded with url: /service/search/detail/pro.bestcrypto (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fc8b6108110>: Failed to establish a new connection: [Errno 110] Connection timed out',))
`

all scanning goes well until PunkSpider, than it breaks with timeout.
