### ISSUE TITLE
BSON Overflow 

### ISSUE THREAD

**Issue by leveled** [DataSploit/datasploit#33]
Running the program against a test domain I ran into this error:

Traceback (most recent call last):
  File "domainOsint.py", line 432, in <module>
    main()
  File "domainOsint.py", line 428, in main
    do_everything(domain)
  File "domainOsint.py", line 391, in do_everything
    result = db.domaindata.insert(dict_to_apend, check_keys=False)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 2212, in insert
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 535, in _insert
    check_keys, manipulate, write_concern, op_id, bypass_doc_val)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 516, in _insert_one
    check_keys=check_keys)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 244, in command
    self._raise_connection_failure(error)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 372, in _raise_connection_failure
    raise error
OverflowError: BSON can only handle up to 8-byte ints

This happened right after the script searched through Shodan, I will try and see if its reproducible.

**Comment by 0xbadshah** [comment]
Can you check if the modified code at https://gist.github.com/Chan9390/105a654398b48d17e4aecf72efc2bcec works without errors ?

**Comment by bardicknowledge** [comment]
Hello @Chan9390, might I suggest changing default=longhandler to parse_int=longhandler?  default is an unrecognized keyword.  See: https://docs.python.org/2.7/library/json.html#json.load

Making that change seemed to do the trick.

**Comment by kingdonko** [comment]
Using @Chan9390 modified code with @bardicknowledge patch works.

**Comment by 0xbadshah** [comment]
Hey @bardicknowledge , thanks for the correction. I have updated the [code](https://gist.github.com/Chan9390/105a654398b48d17e4aecf72efc2bcec).

**Comment by upgoingstar** [comment]
GUI is now more supported now and hence mongodb is not required. Please check out new documentation at https://datasploit.github.io/datasploit/

thanks.
