### ISSUE TITLE
MongoDB Error

### ISSUE THREAD

**Issue by CSNoyes** [DataSploit/datasploit#40]
```
Traceback (most recent call last):
  File "domainOsint.py", line 432, in <module>
    main()
  File "domainOsint.py", line 428, in main
    do_everything(domain)
  File "domainOsint.py", line 391, in do_everything
    result = db.domaindata.insert(dict_to_apend, check_keys=False)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 2212, in insert
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 535, in _insert
    check_keys, manipulate, write_concern, op_id, bypass_doc_val)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 516, in _insert_one
    check_keys=check_keys)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 244, in command
    self._raise_connection_failure(error)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 372, in _raise_connection_failure
    raise error
OverflowError: MongoDB can only handle up to 8-byte ints

```

**Comment by 0xbadshah** [comment]
Same issue as in #33

**Comment by 0xbadshah** [comment]
Can you check if the modified code at https://gist.github.com/Chan9390/105a654398b48d17e4aecf72efc2bcec works without errors ?

**Comment by upgoingstar** [comment]
We are removing mongoDB as of now and introducing CSV reports. If you still wants mongoDB as an output option, code for the same has been commented out. feel free to use the same. 

We will start supporting the mongodb again, very soon.

Meanwhile, a recent git pull should solve your error.
