### ISSUE TITLE
Whois Error

### ISSUE THREAD

**Issue by dport7** [DataSploit/datasploit#44]
Hello! 

Not sure what's happening but I'm getting an error during the whois proces:

```
Traceback (most recent call last):
  File "domainOsint.py", line 432, in <module>
    main()
  File "domainOsint.py", line 428, in main
    do_everything(domain)
  File "domainOsint.py", line 122, in do_everything
    whoisdata = whoisnew(domain)
  File "/home/sdavenport/Tools/datasploit/domain_whois.py", line 15, in whoisnew
    w = whois.whois(domain)
  File "/usr/local/lib/python2.7/dist-packages/whois/__init__.py", line 38, in whois
    return WhoisEntry.load(domain, text)
  File "/usr/local/lib/python2.7/dist-packages/whois/parser.py", line 170, in load
    return WhoisCom(domain, text)
  File "/usr/local/lib/python2.7/dist-packages/whois/parser.py", line 244, in __init__
    raise PywhoisError(text)
whois.parser.PywhoisError: 
Whois Server Version 2.0
```

I verified that I have the most up to date pywhois version. Am I missing something? Thanks!

**Comment by upgoingstar** [comment]
Hi, we are not using pywhois, Instead please use python-whois

Use pip install -r requirements.txt to avoid such issues. Thank you.
