### ISSUE TITLE
ImportError: No module named celery

### ISSUE THREAD

**Issue by SaiGonSeamus** [DataSploit/datasploit#52]
Anyone know of a fix for this?

Debian 8 Python 2.7.9

root@OTX:~/datasploit# C_FORCE_ROOT=root celery -A core worker -l info --concurrency 20
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 9, in <module>
    load_entry_point('celery==3.1.23', 'console_scripts', 'celery')()
  File "/usr/local/lib/python2.7/dist-packages/celery/**main**.py", line 30, in main
    main()
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 309, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 469, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 489, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/utils.py", line 254, in find_app
    symbol_by_name=symbol_by_name, imp=imp,
  File "/usr/local/lib/python2.7/dist-packages/celery/app/utils.py", line 238, in find_app
    sym = imp(app)
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
ImportError: No module named celery

**Comment by 0xbadshah** [comment]
Use `pip install -r requirements.txt` in the datasploit directory to install all python dependencies.

**Comment by SaiGonSeamus** [comment]
I did.

**Comment by 0xbadshah** [comment]
Execute `pip freeze` and comment it.

**Comment by SaiGonSeamus** [comment]
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['**name**'])
  File "/usr/lib/python2.7/dist-packages/pip/**init**.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

**Comment by 0xbadshah** [comment]
I think there is some problem with `pip`. Try reinstalling python `pip`. For more details https://pip.pypa.io/en/stable/installing/ .

**Comment by EvilHat** [comment]
you can try" cd core" directory before "C_FORCE_ROOT=root celery -A core worker -l info --concurrency 20"

**Comment by SaiGonSeamus** [comment]
cd core worked (a bit)

root@DS:~/datasploit-master/core# C_FORCE_ROOT=root celery -A core worker -l info --concurrency 20

 -------------- celery@DS v3.1.23 (Cipater)
---- ***\* ----- 
--- \* **\*  \* -- Linux-4.4.15-1-pve-x86_64-with-debian-8.5
-- \* - ***\* --- 
- *\* ---------- [config]
- *\* ---------- .> app:         core:0x7f0644ad2fd0
- *\* ---------- .> transport:   amqp://guest:**@localhost:5672//
- *\* ---------- .> results:  
- **\* --- \* --- .> concurrency: 20 (prefork)
  -- ******\* ---- 
  --- ****\* ----- [queues]
  -------------- .> celery           exchange=celery(direct) key=celery

[tasks]
  . core.celery.debug_task
  . osint.domain_GooglePDF.run
  . osint.domain_checkpunkspider.checkpunkspider
  . osint.domain_dnsrecords.parse_dns_records
  . osint.domain_emailhunter.emailhunter
  . osint.domain_forumsearch.boardsearch_forumsearch
  . osint.domain_github.github_search
  . osint.domain_history.netcraft_domain_history
  . osint.domain_pagelinks.pagelinks
  . osint.domain_shodan.shodandomainsearch
  . osint.domain_sslinfo.check_ssl_htbsecurity
  . osint.domain_subdomains.run
  . osint.domain_wappalyzer.wappalyzeit
  . osint.domain_whois.whoisnew
  . osint.domain_wikileaks.wikileaks

[2016-08-22 21:13:01,634: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2016-08-22 21:13:01,640: INFO/MainProcess] mingle: searching for neighbors
[2016-08-22 21:13:02,646: INFO/MainProcess] mingle: all alone
[2016-08-22 21:13:02,654: WARNING/MainProcess] celery@DS ready.

but it just hangs there.

**Comment by SaiGonSeamus** [comment]
when I run in another shell

root@DS:~/datasploit-master/core# python manage.py runserver 0.0.0.0:8000
Performing system checks...

System check identified no issues (0 silenced).
August 22, 2016 - 21:29:01
Django version 1.9.8, using settings 'core.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Not Found: /
[22/Aug/2016 21:29:33] "GET / HTTP/1.1" 404 2012
Not Found: /
[22/Aug/2016 21:29:34] "GET / HTTP/1.1" 404 2012
Not Found: /
[22/Aug/2016 21:29:37] "GET / HTTP/1.1" 404 2012

and in the browser in get this

![ds](https://cloud.githubusercontent.com/assets/7721269/17872500/8e784e2e-68ea-11e6-80b5-f725cc001237.png)

**Comment by 0xbadshah** [comment]
Try browsing `0.0.0.0:8000/osint`

**Comment by SaiGonSeamus** [comment]
It is on a VM but doing

python manage.py runserver IPOFTHEVM:8000

followed by 

IPOFTHEVM:8000/osint

That seems to work.

Still having problems getting the script to run so it just hangs.

**Comment by 0xbadshah** [comment]
I just use `python manage.py runserver` and automatically browse to the IP address of VM with port 8000

**Comment by SaiGonSeamus** [comment]
This is now appearing.

ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.

**Comment by SaiGonSeamus** [comment]
anybody else getting this?

error at /osint/search
[Errno 111] Connection refused
Request Method: POST
Request URL:    http://192.168.1.125:8000/osint/search
Django Version: 1.9.8
Exception Type: error
Exception Value:  
[Errno 111] Connection refused
Exception Location: /usr/local/lib/python2.7/dist-packages/amqp/transport.py in **init**, line 95
Python Executable:  /usr/bin/python
Python Version: 2.7.9
Python Path:  
['/home/seamus/datasploit/core',
 '/usr/local/lib/python2.7/dist-packages/pip-8.1.2-py2.7.egg',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/pymodules/python2.7',
 '/home/seamus/datasploit/core']
Server time:    Fri, 2 Sep 2016 03:17:25 +0000

**Comment by upgoingstar** [comment]
Celery is no more required. please git pull and refer to latest documentation https://datasploit.github.io/datasploit
