### ISSUE TITLE
Error while Performing passive SSL Scan

### ISSUE THREAD

**Issue by SaiGonSeamus** [DataSploit/datasploit#54]
---> Performing passive SSL Scan

Picking up One IP from bunch of IPs returned: xxx.xxx.xxx.xxx
Traceback (most recent call last):
  File "domainOsint.py", line 435, in <module>
    main()
  File "domainOsint.py", line 431, in main
    do_everything(domain)
  File "domainOsint.py", line 299, in do_everything
    results_new = check_ssl_htbsecurity(results['MULTIPLE_IPS'][0])
  File "/root/datasploit-master/domain_sslinfo.py", line 15, in check_ssl_htbsecurity
    req = requests.post('https://www.htbridge.com/ssl/chssl/1451425590.html', headers=headers , data=data)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 362, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 854, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 253, in sendall
    sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 242, in _send_until_done
    return self.connection.send(data)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 947, in send
    raise TypeError("data must be a byte string")
TypeError: data must be a byte string

**Comment by SaiGonSeamus** [comment]
I still see this but it is not consistent between scans on different domains, about 50% fail.

**Comment by n0skill** [comment]
I am facing the same issue

**Comment by 0xbadshah** [comment]
The script `domain_sslinfo.py` currently has some issues. It would be updated soon.

**Comment by Dargin** [comment]
Commented on https://github.com/upgoingstar/datasploit/issues/68 - changing the URL and modifying the results should work, "VALUE" doesn't seem to be in the new api so have to figure out what's useful

**Comment by upgoingstar** [comment]
closed as #68
