### ISSUE TITLE
Finding Pagelinks: List index out of range

### ISSUE THREAD

**Issue by NoahJaehnert** [DataSploit/datasploit#59]
Hello,

When running datasploit on a domain, I'm getting the following error in the Finding Pagelinks module/section: 

```
---> Finding Pagelinks:
<removed list of links to save space> 

Traceback
 (most recent call last):
  File "domainOsint.py", line 435, in <module>
    main()
  File "domainOsint.py", line 431, in main
    do_everything(domain)
  File "domainOsint.py", line 265, in do_everything
    subdomains_from_netcraft(domain)
  File "/datasploit/domain_subdomains.py", line 150, in subdomains_from_netcraft
    if num_subdomains[0] != str(0):
IndexError: list index out of range
```

Any thoughts?

**Comment by k0takaiz** [comment]
Posting a comment here to say that I am receiving the same error.

**Comment by upgoingstar** [comment]
I tried reproducing the error but cannot crash into the same. 
1. Are u using latest code? 
2. If you are still facing the same, please send me the domain name you are trying on.

**Comment by FelipeDelgado** [comment]
I'm having the same problem.
```
Traceback (most recent call last):
  File "domainOsint.py, line 374, in <module>
    main()
  File "domainOsint.py", line 263, in do_everything
    subdomains_from_netcraft(domain)
  File "/root/Documents/datasplit/domain_subdomains.py", line 152, in subdomains_from_netcraft
    if num_subdomains[0] != str(0):
IndexError: list out of range
```
I cloned the repo yesterday.

**Comment by upgoingstar** [comment]
believe this is fixed by now. Please check and raise the issue if it still persists. thanks.
