### ISSUE TITLE
Error : Finding User Information

### ISSUE THREAD

**Issue by SaiGonSeamus** [DataSploit/datasploit#61]
---> Finding User Information

Traceback (most recent call last):
  File "domainOsint.py", line 435, in <module>
    main()
  File "domainOsint.py", line 431, in main
    do_everything(domain)
  File "domainOsint.py", line 222, in do_everything
    print_emailosint(x)
  File "/home/seamus/datasploit/emailOsint.py", line 82, in print_emailosint
    data = fullcontact(email)
  File "/home/seamus/datasploit/email_fullcontact.py", line 14, in fullcontact
    req = requests.get("https://api.fullcontact.com/v2/person.json?email=%s&apiKey=%s" % (email, cfg.fullcontact_api))
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

**Comment by upgoingstar** [comment]
As per the error, it looks like an error in API key. Have you entered fullcontact_api in config.py

It should look something like below:

fullcontact_api = "XXXXXXXXXX"
