### ISSUE TITLE
Errors while using web UI

### ISSUE THREAD

**Issue by SrGodrik** [DataSploit/datasploit#64]
1st. Get following errors about shodan and emailhunter:

[2016-09-04 12:03:22,068: ERROR/MainProcess] Task osint.domain_emailhunter.emailhunter[80edd1d7-c720-4094-8f82-bfa7a5cc0ae7] raised unexpected: AttributeError("'module' object has no attribute 'emailhunter'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in **protected_call**
    return self.run(_args, *_kwargs)

 File "/root/datasploit/core/osint/domain_emailhunter.py", line 12, in emailhunter
    if config.emailhunter:
AttributeError: 'module' object has no attribute 'emailhunter'
[2016-09-04 12:03:22,097: ERROR/MainProcess] Task osint.domain_shodan.shodandomainsearch[0b00e584-feb3-4c43-9ecb-48ff88bfa632] raised unexpected: AttributeError("'module' object has no attribute 'shodan_api'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in **protected_call**
    return self.run(_args, *_kwargs)
  File "/root/datasploit/core/osint/domain_shodan.py", line 15, in shodandomainsearch
    if config.shodan_api:
AttributeError: 'module' object has no attribute 'shodan_api'

2nd. Lies about number of subdomain and just freeze:) 
[2016-09-04 12:03:30,069: WARNING/Worker-6] zero subdomains found here
[2016-09-04 12:03:30,085: INFO/MainProcess] Task osint.domain_subdomains.run[d0093775-9432-4d23-bb35-0590dc727bb9] succeeded in 8.03900062s: [u'gp.somedomain', u'gp-ss.somadomain', u'vpn.somedomain', u'familyhistory.somedomain', u'somedomain',...

**Comment by upgoingstar** [comment]
WEB Ui is currently broken and we are thinking of restructuring the WEB ui part to make the program more effective.

**Comment by upgoingstar** [comment]
We have closed web UI now.
