### ISSUE TITLE
Netcraft : KeyError: "name='csrftoken', domain=None, path=None"

### ISSUE THREAD

**Issue by SaiGonSeamus** [DataSploit/datasploit#66]
This is has turning up of late, anyone else see this?

---> Searching Domain history in Netcraft

Traceback (most recent call last):
  File "domainOsint.py", line 435, in <module>
    main()
  File "domainOsint.py", line 431, in main
    do_everything(domain)
  File "domainOsint.py", line 249, in do_everything
    subdomains(domain)
  File "/home/seamus/datasploit/domain_subdomains.py", line 30, in subdomains
    cookies['csrftoken'] = r.cookies['csrftoken']
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 293, in **getitem**
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 351, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by 0xbadshah** [comment]
Can you describe how to reproduce the same error ?

**Comment by SaiGonSeamus** [comment]
I haven't had it since.

**Comment by 0xbadshah** [comment]
Then **close the issue** as this may be a false positive
