### ISSUE TITLE
passive SSL : ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by SaiGonSeamus** [DataSploit/datasploit#67]
---> Performing passive SSL Scan

Traceback (most recent call last):
  File "domainOsint.py", line 435, in <module>
    main()
  File "domainOsint.py", line 431, in main
    do_everything(domain)
  File "domainOsint.py", line 291, in do_everything
    results = check_ssl_htbsecurity(domain)
  File "/home/seamus/datasploit/domain_sslinfo.py", line 16, in check_ssl_htbsecurity
    results = json.loads(req.content)
  File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by upgoingstar** [comment]
Refer to closed issue #68
