### ISSUE TITLE
celery related issue (no such table: celery_taskmeta)

### ISSUE THREAD

**Issue by mykolasglinskis** [DataSploit/datasploit#75]
[2016-10-27 10:47:25,109: INFO/Worker-15] Starting new HTTPS connection (1): search.wikileaks.org
[2016-10-27 10:47:25,128: CRITICAL/MainProcess] Task osint.domain_shodan.shodandomainsearch[d945d4d1-f0b8-4f7a-978a-e10193ee2d87] INTERNAL ERROR: OperationalError('no such table: celery_taskmeta',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 253, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 201, in on_error
    R = I.handle_error_state(task, eager=eager)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 85, in handle_error_state
    }[self.state](task, store_errors=store_errors)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 118, in handle_failure
    req.id, exc, einfo.traceback, request=req,
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 133, in mark_as_failure
    traceback=traceback, request=request)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 271, in store_result
    request=request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/djcelery/backends/database.py", line 29, in _store_result
    traceback=traceback, children=self.current_task_children(request),
  File "/usr/local/lib/python2.7/dist-packages/djcelery/managers.py", line 42, in _inner
    return fun(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/djcelery/managers.py", line 181, in store_result
    'meta': {'children': children}})
  File "/usr/local/lib/python2.7/dist-packages/djcelery/managers.py", line 87, in update_or_create
    return get_queryset(self).update_or_create(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/djcelery/managers.py", line 70, in update_or_create
    obj, created = self.get_or_create(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 465, in get_or_create
    return self.get(**lookup), False
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 381, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 240, in **len**
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 95, in **exit**
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: celery_taskmeta

**Comment by 0xbadshah** [comment]
What version of celery are you using ? Execute command `pip freeze` and comment the output.

**Comment by upgoingstar** [comment]
@mykolasglinskis Did the change recommended by @Chan9390 worked? If you are still facing the same problem, please feel free to re-open the same. Thanks.

**Comment by MrJester** [comment]
I'm running into this same issue and I have the requested versions for celery. I am installing this on a fully updated version of Kali Linux 64-bit

root@<hostname>:/opt/datasploit/core# pip freeze|grep cel
Warning: cannot find svn location for chirp===daily-20170124
celery==3.1.23
django-celery==3.1.17
