### ISSUE TITLE
host='api.hackertarget.com' die

### ISSUE THREAD

**Issue by FreelancePentester** [DataSploit/datasploit#83]
---> Finding Pagelinks:

Traceback (most recent call last):
  File "domainOsint.py", line 388, in <module>
    main()
  File "domainOsint.py", line 384, in main
    do_everything(domain)
  File "domainOsint.py", line 243, in do_everything
    links=pagelinks(domain)	
  File "/home/ddos/Downloads/datasploit/domain_pagelinks.py", line 14, in pagelinks
    req = requests.get('http://api.hackertarget.com/pagelinks/?q=%s'%(domain))
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='api.hackertarget.com', port=80): Max retries exceeded with url: /pagelinks/?q=vnexpress.net (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f783f8aee50>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by 0xbadshah** [comment]
It's just a connection timed out error. Try again.

**Comment by upgoingstar** [comment]
hey @FreelancePentester I hope you have got this solved, and hence closing the same. Please reopen if the issue still persists.

**Comment by FreelancePentester** [comment]
thanks. It has been solved...
