### ISSUE TITLE
Finding hosts from ZoomEye - KeyError: 'access_token'

### ISSUE THREAD

**Issue by mrmookie** [DataSploit/datasploit#84]
I've added my e-mail and password for zoomeyeuser and zoomeyepass in the config.py file yet I get the following error in the Finding hosts from ZoomEye section - KeyError: 'access_token'. When I test the credentials at https://sso.telnet404.com/ it logs in without an issue. Am I missing something? Here is the full error.

---> Finding hosts from ZoomEye

Traceback (most recent call last):
  File "domainOsint.py", line 388, in <module>
    main()
  File "domainOsint.py", line 384, in main
    do_everything(domain)
  File "domainOsint.py", line 290, in do_everything
    zoomeye_results = search_zoomeye(domain)
  File "/home/datasploit/datasploit/domain_zoomeye.py", line 25, in search_zoomeye
    zoomeye_token = get_accesstoken_zoomeye(domain)
  File "/home/datasploit/datasploit/domain_zoomeye.py", line 18, in get_accesstoken_zoomeye
    access_token1 = responsedata['access_token']
KeyError: 'access_token'

**Comment by nixawk** [comment]
Please view https://github.com/ZoomEye/SDK

**Comment by SaiGonSeamus** [comment]
I have the same issue. Was working perfectly before, I have installed the SDK, I have a zoomeye account. 

```
Traceback (most recent call last):
  File "domainOsint.py", line 408, in <module>
    main()
  File "domainOsint.py", line 379, in main
    do_everything(domain)
  File "domainOsint.py", line 306, in do_everything
    zoomeye_results = search_zoomeye(domain)
  File "/root/datasploit/domain_zoomeye.py", line 25, in search_zoomeye
    zoomeye_token = get_accesstoken_zoomeye(domain)
  File "/root/datasploit/domain_zoomeye.py", line 18, in get_accesstoken_zoomeye
    access_token1 = responsedata['access_token']
KeyError: 'access_token'
```

**Comment by mrmookie** [comment]
I've been unable to find a solution so far. Logging into the telnet404 site with credentials works fine, testing their API or trying to use domainOSint.py returns an authentication error.

**Comment by upgoingstar** [comment]
Are you username in zoomeyeuser.
This field requires the emailID which you used to sign up. I noticed it was wrong in documentation, updated the same.

**Comment by upgoingstar** [comment]
Last heading > http://datasploit.readthedocs.io/en/latest/apiGeneration/

Works well for me in multiple environments.

**Comment by upgoingstar** [comment]
believe this is fixed now, please check and open the issue if it still persists.
