### ISSUE TITLE
New error on latest code

### ISSUE THREAD

**Issue by SaiGonSeamus** [DataSploit/datasploit#85]
Traceback (most recent call last):
  File "domainOsint.py", line 391, in <module>
    main()
  File "domainOsint.py", line 362, in main
    do_everything(domain)
  File "domainOsint.py", line 271, in do_everything
    print "%s (%s)" % (lnk, tl)
UnicodeEncodeError: 'ascii' codec can't encode character u'\x91' in position 86: ordinal not in range(128)

**Comment by upgoingstar** [comment]
I believe this would have been fixed by now, please check and raise the issue back in case the problem still persists.
