### ISSUE TITLE
emailOsint.py - AttributeError: 'module' object has no attribute 'mailboxlayer_api'

### ISSUE THREAD

**Issue by johnlittle4550** [DataSploit/datasploit#95]
root@nethunterarch:/opt/datasploit# python emailOsint.py john@arcsecurity.net

---> Basic Email Check(s)..

Traceback (most recent call last):
  File "emailOsint.py", line 233, in <module>
    main()
  File "emailOsint.py", line 229, in main
    print_emailosint(email)
  File "emailOsint.py", line 111, in print_emailosint
    basic_checks(email)
  File "/opt/datasploit/email_basic_checks.py", line 19, in basic_checks
    if cfg.mailboxlayer_api != "" and cfg.mailboxlayer_api != "XYZ" and cfg.mailboxlayer_api != "" and cfg.mailboxlayer_api != "XYZ":
AttributeError: 'module' object has no attribute 'mailboxlayer_api'

**Comment by upgoingstar** [comment]
Please add following entry in your config.py. 

mailboxlayer_api = "XYZ"
where XYZ is your mailboxlayer_api key.
